### ISSUE TITLE
Heb12 Mobile page gives mixed content warnings

### ISSUE THREAD

**Issue by MasterOfTheTiger** [heb12/heb12.github.io#2]
This is due to the link to http://www.businessofapps.com/wp-content/uploads/2014/02/Amazon-App-Store.png which cannot be served over HTTPS.

@pufflegamerz

**Comment by MasterOfTheTiger** [comment]
This is due to the link to http://www.businessofapps.com/wp-content/uploads/2014/02/Amazon-App-Store.png which cannot be served over HTTPS.

@pufflegamerz

**Comment by petabyt** [comment]
Ok. I'll just download it and put it on there.

**Comment by MasterOfTheTiger** [comment]
Fixed in 4562a3634830853114ac0ea0f25f31e7c519b7b8
